global:
  message: Welcome to global microservices environment
logging:
  level:
    root:Info
eureka:
  client:
    service-url:
      defaultZone:http://localhost:8761/eureka
  Management:
    endpoints:
      web:
        exposure:
          include:health,info,refresh
    endpoint:
      health:
        show-details:always
